
import 'package:foods/Food%20model/hotel_class.dart';

List<List> difhot = [
  [
    HotelClass(
        name: 'Neapolitian Pizza',
        des: 'Cheese, Basil and Red Sause ',
        price: 20.94,
        imgurl: 'assets/image/neapolitan_pizza.jpg',
        review: '4.5',
        img2: 'assets/image',
        quantity: 1),
    HotelClass(
        name: 'Chiago Pizza',
        des: 'Cheese,Beef,Pepperoni and peppers',
        price: 22.30,
        imgurl: 'assets/image/chicago_pizza.webp',
        review: '4.5',
        img2: 'assets/image/back.jpg',
        quantity: 1),
    HotelClass(
        name: 'Sicilian Pizza',
        des: 'Robust Sauce,Pepperoni and Cheese',
        price: 30.50,
        imgurl: 'assets/image/sicilian_pizza_2.webp',
        review: '4.2',
        img2: 'assets/image/',
        quantity: 1),
    HotelClass(
        name: 'Greek Pizza',
        des: ' Olive,Cheese,Onion and Cheese ',
        price: 20.99,
        imgurl: 'assets/image/greek_pizza.jpg',
        review: '4.3',
        img2: 'aasets/image',
        quantity: 1),
  ],
  [
    HotelClass(
        name: 'Apple Fritter',
        des: ' sweet and savory ',
        price: 20.94,
        imgurl: 'assets/image/d1.webp',
        review: '4.5',
        img2: 'assets/image',
        quantity: 1),
    HotelClass(
        name: 'Long John',
        des: 'Chocolate covered long john',
        price: 22.30,
        imgurl: 'assets/image/d2.webp',
        review: '4.5',
        img2: 'assets/image/back.jpg',
        quantity: 1),
    HotelClass(
        name: 'Boston Cream',
        des: 'Creamy custard heart and glossy chocolate',
        price: 30.50,
        imgurl: 'assets/image/d3.webp',
        review: '4.2',
        img2: 'assets/image/',
        quantity: 1),
    HotelClass(
        name: 'Paczki',
        des: 'Soft and jam filled',
        price: 20.99,
        imgurl: 'assets/image/d4.webp',
        review: '4.3',
        img2: 'aasets/image',
        quantity: 1),
  ],
  [
    HotelClass(
        name: 'Neapolitian Pizza',
        des: 'Cheese, Basil and Red Sause ',
        price: 20.94,
        imgurl: 'assets/image/neapolitan_pizza.jpg',
        review: '4.5',
        img2: 'assets/image',
        quantity: 1),
    HotelClass(
        name: 'Chiago Pizza',
        des: 'Cheese,Beef,Pepperoni and peppers',
        price: 22.30,
        imgurl: 'assets/image/chicago_pizza.webp',
        review: '4.5',
        img2: 'assets/image/back.jpg',
        quantity: 1),
    HotelClass(
        name: 'Sicilian Pizza',
        des: 'Robust Sauce,Pepperoni and Cheese',
        price: 30.50,
        imgurl: 'assets/image/sicilian_pizza_2.webp',
        review: '4.2',
        img2: 'assets/image/',
        quantity: 1),
    HotelClass(
        name: 'Greek Pizza',
        des: ' Olive,Cheese,Onion and Cheese ',
        price: 20.99,
        imgurl: 'assets/image/greek_pizza.jpg',
        review: '4.3',
        img2: 'aasets/image',
        quantity: 1),
  ],
  [
    HotelClass(
        name: 'Neapolitian Pizza',
        des: 'Cheese, Basil and Red Sause ',
        price: 20.94,
        imgurl: 'assets/image/neapolitan_pizza.jpg',
        review: '4.5',
        img2: 'assets/image',
        quantity: 1),
    HotelClass(
        name: 'Chiago Pizza',
        des: 'Cheese,Beef,Pepperoni and peppers',
        price: 22.30,
        imgurl: 'assets/image/chicago_pizza.webp',
        review: '4.5',
        img2: 'assets/image/back.jpg',
        quantity: 1),
    HotelClass(
        name: 'Sicilian Pizza',
        des: 'Robust Sauce,Pepperoni and Cheese',
        price: 30.50,
        imgurl: 'assets/image/sicilian_pizza_2.webp',
        review: '4.2',
        img2: 'assets/image/',
        quantity: 1),
    HotelClass(
        name: 'Greek Pizza',
        des: ' Olive,Cheese,Onion and Cheese ',
        price: 20.99,
        imgurl: 'assets/image/greek_pizza.jpg',
        review: '4.3',
        img2: 'aasets/image',
        quantity: 1),
  ],
  [
    HotelClass(
        name: 'Neapolitian Pizza',
        des: 'Cheese, Basil and Red Sause ',
        price: 20.94,
        imgurl: 'assets/image/neapolitan_pizza.jpg',
        review: '4.5',
        img2: 'assets/image',
        quantity: 1),
    HotelClass(
        name: 'Chiago Pizza',
        des: 'Cheese,Beef,Pepperoni and peppers',
        price: 22.30,
        imgurl: 'assets/image/chicago_pizza.webp',
        review: '4.5',
        img2: 'assets/image/back.jpg',
        quantity: 1),
    HotelClass(
        name: 'Sicilian Pizza',
        des: 'Robust Sauce,Pepperoni and Cheese',
        price: 30.50,
        imgurl: 'assets/image/sicilian_pizza_2.webp',
        review: '4.2',
        img2: 'assets/image/',
        quantity: 1),
    HotelClass(
        name: 'Greek Pizza',
        des: ' Olive,Cheese,Onion and Cheese ',
        price: 20.99,
        imgurl: 'assets/image/greek_pizza.jpg',
        review: '4.3',
        img2: 'aasets/image',
        quantity: 1),
  ],
  [
    HotelClass(
        name: 'Neapolitian Pizza',
        des: 'Cheese, Basil and Red Sause ',
        price: 20.94,
        imgurl: 'assets/image/neapolitan_pizza.jpg',
        review: '4.5',
        img2: 'assets/image',
        quantity: 1),
    HotelClass(
        name: 'Chiago Pizza',
        des: 'Cheese,Beef,Pepperoni and peppers',
        price: 22.30,
        imgurl: 'assets/image/chicago_pizza.webp',
        review: '4.5',
        img2: 'assets/image/back.jpg',
        quantity: 1),
    HotelClass(
        name: 'Sicilian Pizza',
        des: 'Robust Sauce,Pepperoni and Cheese',
        price: 30.50,
        imgurl: 'assets/image/sicilian_pizza_2.webp',
        review: '4.2',
        img2: 'assets/image/',
        quantity: 1),
    HotelClass(
        name: 'Greek Pizza',
        des: ' Olive,Cheese,Onion and Cheese ',
        price: 20.99,
        imgurl: 'assets/image/greek_pizza.jpg',
        review: '4.3',
        img2: 'aasets/image',
        quantity: 1),
  ],
];
